-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS evergreen;
USE evergreen;

-- Loads table - tracks each CSV import with history
CREATE TABLE IF NOT EXISTS loads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  file_path VARCHAR(500),
  total_records INT,
  successful_records INT,
  failed_records INT,
  status ENUM('pending', 'processing', 'completed', 'failed') DEFAULT 'pending',
  error_message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  uploaded_by VARCHAR(100),
  notes TEXT,
  INDEX idx_status (status),
  INDEX idx_created_at (created_at)
);

-- Properties table - stores all property data from CSV uploads
CREATE TABLE IF NOT EXISTS properties (
  id INT AUTO_INCREMENT PRIMARY KEY,
  mls_id VARCHAR(50),
  address VARCHAR(500) NOT NULL,
  city VARCHAR(100),
  state VARCHAR(50),
  zip_code VARCHAR(10),
  county VARCHAR(100),
  living_square_feet INT,
  year_built INT,
  lot_acres DECIMAL(10, 6),
  lot_square_feet DECIMAL(12, 2),
  land_use VARCHAR(100),
  property_type VARCHAR(100),
  property_use VARCHAR(100),
  subdivision VARCHAR(255),
  apn VARCHAR(100),
  legal_description TEXT,
  units_count INT,
  bedrooms INT,
  bathrooms DECIMAL(3, 1),
  stories INT,
  garage_type VARCHAR(100),
  garage_square_feet INT,
  carport VARCHAR(100),
  carport_area DECIMAL(10, 2),
  air_conditioning_type VARCHAR(100),
  heating_type VARCHAR(100),
  fireplaces INT,
  owner1_first_name VARCHAR(100),
  owner1_last_name VARCHAR(100),
  owner_mailing_address VARCHAR(500),
  owner_mailing_city VARCHAR(100),
  owner_mailing_state VARCHAR(50),
  owner_mailing_zip VARCHAR(10),
  ownership_length_months INT,
  owner_type VARCHAR(100),
  owner_occupied VARCHAR(50),
  vacant VARCHAR(50),
  listing_status VARCHAR(100),
  listing_price DECIMAL(12, 2),
  days_on_market INT,
  last_updated VARCHAR(100),
  agent_name VARCHAR(255),
  agent_first_name VARCHAR(100),
  agent_last_name VARCHAR(100),
  agent_email VARCHAR(255),
  agent_phone VARCHAR(20),
  brokerage_name VARCHAR(255),
  brokerage_phone VARCHAR(20),
  mls_type VARCHAR(50),
  last_sale_date VARCHAR(50),
  last_sale_amount DECIMAL(12, 2),
  estimated_value DECIMAL(12, 2),
  estimated_equity DECIMAL(12, 2),
  market_value DECIMAL(12, 2),
  tax_amount DECIMAL(12, 2),
  assessment_year INT,
  assessed_total_value DECIMAL(12, 2),
  ghl_sync_status ENUM('not_synced', 'synced', 'failed') DEFAULT 'not_synced',
  ghl_sync_date TIMESTAMP NULL,
  ghl_error_message TEXT,
  sync_enabled BOOLEAN DEFAULT true,
  rental_income DECIMAL(12, 2),
  mortgage_principal DECIMAL(12, 2),
  mortgage_rate DECIMAL(5, 3),
  mortgage_term INT,
  estimated_arv DECIMAL(12, 2),
  estimated_repair_cost DECIMAL(12, 2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  load_id INT NOT NULL,
  FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE CASCADE,
  INDEX idx_load_id (load_id),
  INDEX idx_agent_email (agent_email),
  INDEX idx_mls_id (mls_id),
  INDEX idx_ghl_sync_status (ghl_sync_status),
  INDEX idx_city_state (city, state),
  INDEX idx_created_at (created_at)
);

-- GoHighLevel automations log - track which automations were triggered
CREATE TABLE IF NOT EXISTS ghl_automations_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  property_id INT NOT NULL,
  load_id INT NOT NULL,
  agent_email VARCHAR(255),
  agent_phone VARCHAR(20),
  automation_type ENUM('email', 'sms', 'webhook') DEFAULT 'email',
  status ENUM('pending', 'sent', 'failed') DEFAULT 'pending',
  ghl_response JSON,
  error_message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  sent_at TIMESTAMP NULL,
  FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
  FOREIGN KEY (load_id) REFERENCES loads(id) ON DELETE CASCADE,
  INDEX idx_property_id (property_id),
  INDEX idx_status (status)
);

-- Property analysis - stores deal analysis results and investment criteria scoring
CREATE TABLE IF NOT EXISTS property_analysis (
  id INT AUTO_INCREMENT PRIMARY KEY,
  property_id INT NOT NULL UNIQUE,
  analysis_type ENUM('subto', 'owner_financing', 'multi_family', 'unknown') DEFAULT 'unknown',
  overall_score VARCHAR(20),
  state_pass BOOLEAN,
  state_pass_reason VARCHAR(500),
  cashflow_positive BOOLEAN,
  cashflow_amount DECIMAL(12, 2),
  subto_criteria_met BOOLEAN,
  subto_failures JSON,
  owner_financing_criteria_met BOOLEAN,
  owner_financing_failures JSON,
  multi_family_criteria_met BOOLEAN,
  multi_family_failures JSON,
  dscr_loan_qualified BOOLEAN,
  dscr_monthly_required DECIMAL(12, 2),
  financing_option_asking DECIMAL(12, 2),
  financing_option_asking_rate DECIMAL(5, 3),
  financing_option_above_asking DECIMAL(12, 2),
  financing_option_above_asking_rate DECIMAL(5, 3),
  green_light BOOLEAN,
  yellow_light BOOLEAN,
  red_light BOOLEAN,
  analysis_notes TEXT,
  recommendation VARCHAR(500),
  input_assumptions JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
  INDEX idx_property_id (property_id),
  INDEX idx_overall_score (overall_score),
  INDEX idx_created_at (created_at)
);
